# Generated by Django 4.1.5 on 2023-01-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=30)),
                ('heading', models.CharField(max_length=100)),
                ('paragraph', models.CharField(max_length=10000)),
            ],
        ),
    ]
