from django.urls import path

from . import views

urlpatterns = [
    path('dashboard/', views.index, name='dashboard-index'),
    path('products/', views.products, name='dashboard-products'),
    path('products/delete/<int:pk>/', views.product_delete, name='dashboard-products-delete'),
    path('products/detail/<int:pk>/', views.product_detail, name='dashboard-product-detail'),
    path('products/edit/<int:pk>/', views.product_edit, name='dashboard-products-edit'),
    path('customers/', views.customers, name='dashboard-customers'),
    path('customers/details/<int:pk>', views.customer_detail, name='dashboard-customer-detail'),
    path('order/', views.order, name='dashboard-order'),
    path('mail_sending/', views.mail_sending, name='dashboard-mail_sending'),
    path('navbar_customize/', views.navbar_customize, name='dashboard-navbar_customize'),
    path('navbar_customize/delete/<int:pk>/', views.navbar_customize_delete, name='dashboard-navbar_customize_delete'),
    path('navbar_customize/edit/<int:pk>/', views.navbar_customize_edit, name='dashboard-navbar_customize_edit'),
    path('homedetails_customize/', views.homedetails_customize, name='dashboard-homedetails_customize'),
    path('homedetails_customize/delete/<int:pk>/', views.homedetails_customize_delete,
         name='dashboard-homedetails_customize_delete'),
    path('homedetails_customize/edit/<int:pk>/', views.homedetails_customize_edit,
         name='dashboard-homedetails_customize_edit'),
    path('about_customize/', views.about_customize, name='dashboard-about_customize'),
    path('about_customize/delete/<int:pk>/', views.about_customize_delete,
         name='dashboard-about_customize_delete'),
    path('about_customize/edit/<int:pk>/', views.about_customize_edit,
         name='dashboard-about_customize_edit'),
    path('menu_customize/', views.menu_customize, name='dashboard-menu_customize'),
    path('menu_customize/delete/<int:pk>/', views.menu_customize_delete,
         name='dashboard-menu_customize_delete'),
    path('menu_customize/edit/<int:pk>/', views.menu_customize_edit,
         name='dashboard-menu_customize_edit'),
    path('offer_customize/', views.offer_customize, name='dashboard-offer_customize'),
    path('offer_customize/delete/<int:pk>/', views.offer_customize_delete,
         name='dashboard-offer_customize_delete'),
    path('offer_customize/edit/<int:pk>/', views.offer_customize_edit,
         name='dashboard-offer_customize_edit'),
    path('work_customize/', views.work_customize, name='dashboard-work_customize'),
    path('work_customize/delete/<int:pk>/', views.work_customize_delete,
         name='dashboard-work_customize_delete'),
    path('work_customize/edit/<int:pk>/', views.work_customize_edit,
         name='dashboard-work_customize_edit'),
    path('brand_customize/', views.brand_customize, name='dashboard-brand_customize'),
    path('brand_customize/delete/<int:pk>/', views.brand_customize_delete,
         name='dashboard-brand_customize_delete'),
    path('brand_customize/edit/<int:pk>/', views.brand_customize_edit,
         name='dashboard-brand_customize_edit'),
    path('reviews_customize/', views.reviews_customize, name='dashboard-reviews_customize'),
    path('reviews_customize/delete/<int:pk>/', views.reviews_customize_delete,
         name='dashboard-reviews_customize_delete'),
    path('reviews_customize/edit/<int:pk>/', views.reviews_customize_edit,
         name='dashboard-reviews_customize_edit'),
    path('newsletter_customize/', views.newsletter_customize, name='dashboard-newsletter_customize'),
    path('newsletter_customize/delete/<int:pk>/', views.newsletter_customize_delete,
         name='dashboard-newsletter_customize_delete'),
    path('newsletter_customize/edit/<int:pk>/', views.newsletter_customize_edit,
         name='dashboard-newsletter_customize_edit'),

]
